INSERT INTO 
	T_UMS_SEND_DETAIL
		(
			DETAIL_SEQNO,	UMS_SEQNO,CUID,	CNAME,	MMS_SEQNO,	SEND_MSG,	MSG_VARS,	
			MOBILE_NUM,	SEND_KIND,	STATUS,	ERRCODE,	RESULTMSG,	REGDATE,
			TRANS_TABLE,TRANS_SEQNO
		)
VALUES
		(
			SEQ_UMS_SENDDETAIL.NEXTVAL,${MASTERTABLE_SEQNO},${CUID},${CNAME},${MMS_SEQNO},${SEND_MSG},${MSG_VARS},
			${MOBILE_NUM},	${SEND_KIND},	${STATUS},	${ERRCODE},	${RESULTMSG},	SYSDATE,
			${TRANS_TABLE},	${TRANS_SEQNO}
		)