UPDATE 
		T_UMS_SEND_DETAIL 
SET 
		STATUS=${STATUS}, PROCESS_END='Y', ERRCODE=${ERRCODE},
		RESULTMSG=${RESULTMSG}, MODDATE=SYSDATE  
WHERE 	KKO_ALT_SEQNO=${MESSAGE_SEQNO} 
AND 	MOBILE_NUM=${RECEIVE_MOBILE_NO}