insert into 
 	SMSBATHT
 		(
 			TR_NUM, TR_SENDDATE, TR_ID, TR_SENDSTAT, TR_MSGTYPE, 
 			TR_PHONE_ENC, TR_CALLBACK_ENC, TR_ETC1, TR_ETC2, TR_ETC3,
			TR_ETC4, TR_LONGMSG, TR_IMG1, TR_IMG2, TR_IMG3, TR_PUSHMSG,TRAN_SN,AGENT_ID
		)
values
		(
			SMS_SEQUENCE.NEXTVAL, SYSDATE, ${UMS_SENDMSG_SEQNO}, ${TR_SENDSTAT}, ${TR_MSGTYPE}, 
			${RECEIVE_MOBILE_NO}, ${CALLBACK}, ${TR_ETC1}, ${TR_ETC2}, ${TR_ETC3},
        	${TR_ETC4},${TR_LONGMSG},${TR_IMG1},${TR_IMG2},${TR_IMG3},${TR_PUSHMSG}, ${TRAN_SN},${AGENT_ID}
        )